{% set name = "napari-nifti" %}
{% set version = "0.0.17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: a74b8bc4b6d4c47a1c88771f91eef240721a26b033be511e119e2e57b28e6e1d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - numpy
    - python >=3.8
    - simpleitk

test:
  imports:
    - napari_nifti
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/MIC-DKFZ/napari-nifti
  summary: |
    A napari plugin for reading and writing NIFTI files that have
    the extension .nii or .nii.gz.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - Karol-G
